import { Timestamp } from "firebase/firestore";

// Main drawing interface
export interface Drawing {
  id: string;
  estimateId?: string;
  mode: DrawingMode;
  createdAt: Timestamp | string;
  lastModified: Timestamp | string;
  thumbnailUrl: string;
  fullImageUrl: string;
  metadata: DrawingMetadata;
  data: AutoGeneratedData | PhotoAnnotationData | InteractiveBuilderData;
}

export type DrawingMode = 'auto-generated' | 'photo-annotation' | 'interactive-builder';

export interface DrawingMetadata {
  canvasWidth: number;
  canvasHeight: number;
  scale?: number;
  units?: 'feet' | 'meters';
}

// Auto-generated diagram data
export interface AutoGeneratedData {
  type: 'auto-generated';
  jobType: string;
  sourceData: Record<string, any>;
  elements: KonvaElement[];
}

export interface KonvaElement {
  type: 'rect' | 'line' | 'circle' | 'text' | 'image';
  [key: string]: any;
}

// Photo annotation data
export interface PhotoAnnotationData {
  type: 'photo-annotation';
  basePhotoUrl: string;
  basePhotoName: string;
  annotations: Annotation[];
}

export interface Annotation {
  id: string;
  type: AnnotationType;
  color: string;
  strokeWidth: number;
  points?: number[];
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  radius?: number;
  text?: string;
  fontSize?: number;
}

export type AnnotationType = 'line' | 'arrow' | 'rectangle' | 'circle' | 'text' | 'freehand';

// Interactive builder data
export interface InteractiveBuilderData {
  type: 'interactive-builder';
  components: BuilderComponent[];
  gridSize: number;
  snapToGrid: boolean;
}

export interface BuilderComponent {
  id: string;
  type: ComponentType;
  x: number;
  y: number;
  width?: number;
  height?: number;
  rotation: number;
  properties: ComponentProperties;
}

export type ComponentType =
  | 'post'
  | 'beam'
  | 'joist'
  | 'railing'
  | 'stairs'
  | 'ledger'
  | 'decking';

export interface ComponentProperties {
  size?: string;
  length?: number;
  material?: string;
  color?: string;
  label?: string;
}

// Drawing tool state
export interface DrawingToolState {
  tool: AnnotationType;
  color: string;
  strokeWidth: number;
}

// Props interfaces for components
export interface DrawingModalProps {
  isOpen: boolean;
  onClose: () => void;
  jobData: any;
  uploadedFiles: any[];
  onSaveDrawing: (drawing: Drawing) => void;
  existingDrawing?: Drawing;
}

export interface DrawingGalleryProps {
  drawings: Drawing[];
  onEdit: (drawing: Drawing) => void;
  onDelete: (id: string) => void;
}

export interface CanvasToolbarProps {
  onZoomIn: () => void;
  onZoomOut: () => void;
  onResetView: () => void;
  onUndo?: () => void;
  onRedo?: () => void;
  onSave: () => void;
  onExport: () => void;
  showGrid?: boolean;
  onToggleGrid?: () => void;
  canUndo?: boolean;
  canRedo?: boolean;
}

export interface AutoDiagramCanvasProps {
  jobData: any;
  onExport: (dataURL: string) => void;
}

export interface PhotoAnnotationCanvasProps {
  photoUrl: string;
  photoName: string;
  initialAnnotations?: Annotation[];
  onExport: (dataURL: string) => void;
}

export interface BuilderCanvasProps {
  initialComponents?: BuilderComponent[];
  onExport: (dataURL: string) => void;
}
